server:
  port: 3020

nest:
  app-name: gateway
  datasource:
    mysql:
      name: 'mcx-wms'
      type: 'mysql'
      host: 'localhost'
      port: 3306
      database: 'mcx-wms'
      username: 'root'
      password: '123456'
      entities: 'mysql'
      synchronize: true
    mongodb:
      url: mongodb://localhost:27017
      database: gateway
      type: mongodb
      entities: mongo
      logging: true
      synchronize: true
    redis:
      name: 'gateway'
      host: 'localhost'
      port: 6379
      keyPrefix: 'gateway'
